export const CANONICAL_CATEGORY_NAMES = [
  "Electricidad",
  "Plomer\u00EDa",
  "Carpinter\u00EDa",
  "Pintura",
  "Aires acondicionados",
  "Cerrajer\u00EDa",
  "Reformas",
  "Jardiner\u00EDa",
  "Limpieza",
  "Mudanzas",
  "Fumigaci\u00F3n",
  "Impermeabilizaci\u00F3n",
  "Instalaci\u00F3n de pisos",
  "Techos y cubiertas",
  "Soldadura",
  "Vidrier\u00EDa",
  "Alarmas y CCTV",
  "Electrodom\u00E9sticos",
  "Otro",
] as const;
